### ISSUE TITLE
Questions to Kamailio Konfiguration and CCM

### ISSUE THREAD

**Issue by Harunbk** [IrisBroadcast/ccm#1]
Hello,

thank you for providing this project. I want to use it, but I have a few questions.

I did setup the CCM on Visual Studio with a mysql database. The website runs flawless. I receive data from the kamailio via the Rest-API. But the database only save data in tables "registeredsips" and "log". The other tables are empty. In the log table we cant find any database exception.

Is it necessary to login in order to use it correctly?
How can I sign up a user(admin) on the CCM?

I look forward to your reply. 

Thank you in advance!
Best regards

harunbk

**Comment by oej** [comment]
I will fix the typo in kamailio.cfg.

**Comment by oej** [comment]
Please report the kamailio issues in the "connect" project - the kamailio config is a separate repository. Thanks.

**Comment by Harunbk** [comment]
> I will fix the typo in kamailio.cfg.

Thanks !!

> Please report the kamailio issues in the "connect" project - the kamailio config is a separate repository. Thanks.

I have split the question now.

**Comment by Roog** [comment]
Hi @Harunbk 
We missed to provide a first ccm-user when we publish this. So you'll need to add it manually. Unless you've managed to create all the tables, you can just insert a ccmuser in the table. 

This one would add a "root:root" user. Hope this works for you? We'll publish some more example data, and basic data you'll need to get started!

`CREATE TABLE `ccmusers` (
  `Id` char(36) COLLATE utf8mb4_swedish_ci NOT NULL,
  `UserName` longtext COLLATE utf8mb4_swedish_ci,
  `FirstName` longtext COLLATE utf8mb4_swedish_ci,
  `LastName` longtext COLLATE utf8mb4_swedish_ci,
  `Comment` longtext COLLATE utf8mb4_swedish_ci,
  `PasswordHash` longtext COLLATE utf8mb4_swedish_ci,
  `Salt` longtext COLLATE utf8mb4_swedish_ci,
  `CreatedBy` longtext COLLATE utf8mb4_swedish_ci,
  `CreatedOn` datetime NOT NULL,
  `UpdatedBy` longtext COLLATE utf8mb4_swedish_ci,
  `UpdatedOn` datetime NOT NULL,
  `Role_Id` char(36) COLLATE utf8mb4_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_CcmUsers_Role_RoleId` (`Role_Id`),
  CONSTRAINT `FK_CcmUsers_Roles_RoleId` FOREIGN KEY (`Role_Id`) REFERENCES `roles` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_swedish_ci;

-- Dumping data for table `ccmusers`
LOCK TABLES `ccmusers` WRITE;
/*!40000 ALTER TABLE `ccmusers` DISABLE KEYS */;
INSERT INTO `ccmusers` VALUES ('C0E480FC-BD0C-4779-8324-85DD709B7FBE','root','root','Administrator',NULL,'kq+3HYdWGXLlrKVtb3Jprg==','NSVoZlkkdSFnclFCZEhzZyMmXiQ=','root','2019-04-15 15:51:44','root','2018-04-25 07:10:09','93F8370B-3321-42CB-A7BF-856AA8E6446E');
/*!40000 ALTER TABLE `ccmusers` ENABLE KEYS */;
UNLOCK TABLES;
`

**Comment by Roog** [comment]
So now, the example data is located on:
https://github.com/IrisBroadcast/CCM/blob/master/CCM.Data/ExampleData/Dump20190417.sql

It's not the bare minimum. But also some example data like accounts (root:root for login), "actual calls" that has not been ended, filter data and location data. So you can try to access the Discovery site and get responses from Active Phonebook / IRIS Discovery. 

Best regards
Roger
